# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    mac:
      imageName: 'macOS-10.15'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:
- task: CMake@1
  inputs:
    cmakeArgs: ../

- task: CMake@1
  inputs:
    cmakeArgs: '--build . --target BirdWatcher'